--drop table NH_USERS;

create table NH_USERS (
    USER_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    USERNAME CHAR(200),
    FIRSTNAME CHAR(200),
    LASTNAME CHAR(200),
    ITEMS BLOB,
    EMAIL CHAR(200),
    PASSWORD CHAR(200),
    PRIMARY KEY (USER_ID)
)

-- Discoveries Page
CREATE TABLE PLANETARY_ENTITY (
    PLANETARY_ENTITY_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    ISPLANET BIT(0),
    ISMOON BIT(0),
    NAME CHAR(64),
    ORBITING_MOON_SURVEY CHAR(200),
    ORBITING_MOON_COUNT TINYINT,
    RING_DATA   CHAR(200),
    IMAGE BLOB,
    ENTRY_LAST_UPDATED DEFAULT CURRENT_TIMESTAMP,
    NAME CHAR(64) NOT NULL UNIQUE,    
    PRIMARY KEY (PLANETARY_ENTITY_ID),
)

